// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Document struct {
	ID          pgtype.UUID
	ProjectID   pgtype.UUID
	OwnerUserID pgtype.UUID
	Title       string
	Content     string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Project struct {
	ID          pgtype.UUID
	Name        string
	WorkspaceID pgtype.UUID
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ProjectMember struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID          pgtype.UUID
	DisplayName string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Workspace struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type WorkspaceMember struct {
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
	Role        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
